#!/bin/sh
if [[ ! -z "$DEIS_USERNAME" ]] && [[ ! -z "$DEIS_CONTROLLER" ]] && [[ ! -z "$DEIS_TOKEN" ]]; then
mkdir -p ~/.deis
cat <<EOF > ~/.deis/${DEIS_PROFILE:-client}.json
{
  "username": "${DEIS_USERNAME}",
  "ssl_verify": ${DEIS_SSL_VERIFY:-true},
  "controller": "${DEIS_CONTROLLER}",
  "token": "${DEIS_TOKEN}",
  "response_limit": ${DEIS_RESPONSE_LIMIT:-100}
}
EOF
elif [[ ! -z "$DEIS_USERNAME" ]] && [[ ! -z "$DEIS_CONTROLLER" ]] && [[ ! -z "$DEIS_PASSWORD" ]]; then
  /usr/bin/deis auth:login "${DEIS_CONTROLLER}" \
    --username="${DEIS_USERNAME}" \
    --password="${DEIS_PASSWORD}" \
    --ssl-verify="${DEIS_SSL_VERIFY:-true}"
fi
exec /usr/bin/deis "$@"
