#!/bin/sh
if [[ ! -z "${DEIS_SSH_KEY:-${GIT_SSH_KEY:-$SSH_KEY}}" ]]; then
  eval `ssh-agent -s` > /dev/null
  echo "${DEIS_SSH_KEY:-${GIT_SSH_KEY:-$SSH_KEY}}" | ssh-add - 2> /dev/null
fi
export GIT_SSH_COMMAND="${GIT_SSH_COMMAND:-ssh -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no}"
exec /usr/bin/git "$@"
